######################################################################
# Automatically generated by qmake (2.01a) ? 11 25 17:33:49 2014
######################################################################

QT += gui widgets

TEMPLATE = app
TARGET = dpxReader
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += DPXimage_Header.h dpxReader.h
SOURCES += dpxReader.cpp
