######################################################################
# Automatically generated by qmake (2.01a) ? 11 5 11:47:59 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
