######################################################################
# Automatically generated by qmake (2.01a) ? 11 4 16:37:47 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += cliplist.h mainwindow.h sheetview.h tablemodel.h
SOURCES += cliplist.cpp main.cpp mainwindow.cpp sheetview.cpp tablemodel.cpp
